-- Seed Courses (local cover images in /public for reliable loading)
INSERT INTO public.courses (slug, name, nc_level, sector, description, short_description, duration, twsp_scholarship, is_assessment_only, cover_image_url) VALUES
('agricultural-crops-production-nc-i', 'Agricultural Crops Production', 'NC I', 'Agriculture', 'Covers the basic skills required to support nursery work, horticultural and agronomic crop production, and irrigation maintenance.', 'Foundational training in crop cultivation and farm maintenance.', '302 hours', 'true', 'false', '/agriculture-training.png'),
('agricultural-crops-production-nc-ii', 'Agricultural Crops Production', 'NC II', 'Agriculture', 'Builds upon foundational agricultural skills, focusing on nursery management, systematic planting, crop maintenance, and post-harvest handling.', 'Intermediate crop production and post-harvest management.', '336 hours', 'true', 'false', '/news-scholarship.png'),
('animal-production-poultry-chicken-nc-ii', 'Animal Production (Poultry-Chicken)', 'NC II', 'Agriculture', 'Covers competencies required for raising poultry and producing chicken for meat or eggs.', 'Training in poultry and chicken production management.', '300 hours', 'true', 'false', '/course-healthcare.png'),
('beauty-care-nail-care-services-nc-ii', 'Beauty Care (Nail Care) Services', 'NC II', 'Beauty/Wellness', 'Develops specialized skills in manicure, pedicure, and hand/foot spa treatments.', 'Professional nail care and spa services.', '150 hours', 'true', 'false', '/course-beauty-care.png'),
('bookkeeping-nc-iii', 'Bookkeeping', 'NC III', 'Business', 'Equips students with the competency to perform bookkeeping functions including journalizing and posting transactions.', 'Advanced recording and management of financial transactions.', '292 hours', 'true', 'false', '/graduate-bookkeeper.png'),
('bread-and-pastry-production-nc-ii', 'Bread and Pastry Production', 'NC II', 'Tourism', 'Covers the preparation and production of bakery products, pastry products, cakes, and desserts.', 'Baking and pastry arts for commercial service.', '141 hours', 'true', 'false', '/course-dressmaking.png'),
('computer-systems-servicing-nc-ii', 'Computer Systems Servicing', 'NC II', 'ICT', 'Covers the installation, configuration, and maintenance of computer systems, networking, and servers.', 'Professional computer maintenance, networking, and server setup.', '280 hours', 'true', 'false', '/graduate-it-support.png'),
('cookery-nc-ii', 'Cookery', 'NC II', 'Tourism', 'Focuses on the preparation of various hot and cold dishes for institutional or commercial kitchens.', 'Professional kitchen skills and food preparation.', '316 hours', 'true', 'false', '/course-hospitality.png'),
('driving-nc-ii', 'Driving', 'NC II', 'Automotive', 'Accredited by the LTO and TESDA, this course covers safe vehicle operation and defensive driving.', 'Professional driving and basic vehicle maintenance.', '118 hours', 'true', 'false', '/hero.png'),
('electrical-installation-maintenance-nc-ii', 'Electrical Installation & Maintenance', 'NC II', 'Construction', 'Covers the installation and maintenance of electrical wiring, lighting and related equipment.', 'Building electrical systems installation and maintenance.', '402 hours', 'true', 'false', '/course-cybersecurity.png'),
('food-beverage-services-nc-ii', 'Food & Beverage Services', 'NC II', 'Tourism', 'Covers the competencies required to provide food and beverage service to guests in various establishments.', 'Professional service and hospitality management.', '356 hours', 'true', 'false', '/course-project-management.png'),
('heo-backhoe-loader-operations-nc-ii', 'HEO - Backhoe Loader Operations', 'NC II', 'Construction', 'Covers pre- and post-operation procedures and productive operation of backhoe loaders.', 'Safe and productive operation of backhoe loader equipment.', '160 hours', 'true', 'false', '/agriculture-training.png'),
('organic-agriculture-production-nc-ii', 'Organic Agriculture Production', 'NC II', 'Agriculture', 'Covers the production of organic fertilizers, organic vegetables, organic chickens, and organic hogs.', 'Sustainable organic farming and fertilization.', '232 hours', 'true', 'false', '/course-project-management.png'),
('smaw-nc-ii', 'Shielded Metal Arc Welding (SMAW)', 'NC II', 'Metals/Engineering', 'Advanced welding techniques for structural steel and industry certification.', 'Professional arc welding and certification.', '268 hours', 'true', 'false', '/graduate-electrician.png'),
('visual-graphic-design-nc-iii', 'Visual Graphic Design', 'NC III', 'ICT', 'Covers the skills for creating visual designs for print and electronic media.', 'Professional graphic design and multimedia production.', '487 hours', 'true', 'false', '/course-ui-ux.png')
ON CONFLICT (slug) DO NOTHING;

-- Seed Announcements
INSERT INTO public.announcements (title, body, target, created_at) VALUES
('TWSP Scholarship Slots Available!', 'Scholarship slots for Bookkeeping NC III, Driving NC II & Agricultural Crops Production NC I under Training for Work Scholarship Program (TWSP) with training benefits. Enroll now - limited slots only. First come, First served.', 'all', '2024-10-28T08:00:00Z'),
('National Women''s Celebration Month Capability Training', 'In March 2024, LISTA hosted a transformative three-day capability training program in support of National Women''s Celebration Month. Thirty women from Gingoog City participated in practical sessions covering urban gardening, composting, soil preparation, and seedling cultivation.', 'all', '2024-03-20T09:00:00Z'),
('Training of Trainers on Rabbitry Production', 'In June 2024, LISTA''s training farm in Lunotan became the venue for a five-day Training of Trainers on Rabbitry Production as an Enterprise - organized by ATI-RTC X. Twenty participants from Bukidnon, Misamis Oriental, and Misamis Occidental underwent intensive training.', 'all', '2024-06-03T12:00:00Z')
ON CONFLICT DO NOTHING;
